sonar.projectKey=cantou
sonar.projectName=Cantou
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**
sonar.exclusions=**/node_modules/**,android/**,build/**,dist/**,coverage/**,coverage-e2e/**,public/**,**/*.dc.html
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
